### PR TITLE
Add PHP Vegas to 2017 groups

### PR DESCRIPTION
**Pull request by aenglander**

### CODE REVIEW

**Comment by chrisspruck** [comment]
Hey Adam! Would you mind putting your group in sorted order (after PHP Limburg)? Thanks!

**Comment by aenglander** [comment]
Sorry about that. In my head I always think of Vegas PHP instead of PHP Vegas.

I amended the original commit for tidiness.

**Comment by chrisspruck** [comment]
No worries. Thanks for updating!

**Review by chrisspruck — APPROVED** [review]

**Comment by chrisspruck** [comment]
@aenglander Sorry - one more thing. Can you merge master into your PR? I'm working via phone and apparently don't have the option to do that in the mobile interface. Thanks!

**Comment by chrisspruck** [comment]
@aenglander Never mind on merging master. Just got it in the desktop version. Thanks again!

**Pull request merged**
