### PR TITLE
[pt-br] Add translation of website to Brazilian Portuguese in parallel with en

### PR DESCRIPTION
**Pull request by royopa**
As discussed in #69

### CODE REVIEW

**Review by rogeriopradoj — APPROVED** [review]

**Comment by rogeriopradoj** [comment]
@ramsey, it sounds that Travis-CI are rejecting this PR, saying "Abuse Detected".

I searched a little bit about, [people say something on granting permission](https://github.com/travis-ci/travis-ci/issues/8626#issuecomment-339270186) again between Travis and GitHub. I did that with [Brazilian fork](https://github.com/PHPTestFestBrasil/phptestfest.org) and asked permission to owners for phpcommunity one.

Have you passed through this before?

**Comment by ramsey** [comment]
Thanks for finding that out. It was confusing to me why the builds weren’t reporting back. I’ve reauthorized phpcommunity with Travis CI.

**Comment by rogeriopradoj** [comment]
Closing and opening again in order to make travis-ci run again.

**Comment by ramsey** [comment]
👍

**Pull request merged**
