### PR TITLE
Extracted info from qa.php.net website

### PR DESCRIPTION
**Pull request by royopa**
Converted the page http://qa.php.net/write-test.php to markdown to use in this tutorial.

### CODE REVIEW

**Comment by heiglandreas** [comment]
Would you mind to include a link to the original page on qa.php.net? That allows future visitors to see where the page came from and whether stuff changed in between…

**Review by royopa — COMMENTED** [review]
I added the links to original page according to @heiglandreas

**Review by rogeriopradoj — APPROVED** [review]
LGTM

**Comment by ramsey** [comment]
What are the hash marks in front of each heading for? (see below)

hashmarks

**Review by royopa — COMMENTED** [review]
I removed the unnecessary marks after @ramsey question.

**Comment by ramsey** [comment]
@royopa Thanks!

**Comment by ramsey** [comment]
I moved the tutorial to `docs/_tutorials/creating-new-test-files.md` and made some typographical and style changes, so I hope you don't mind.

Thanks for contributing!

**Pull request merged**
