### PR TITLE
Added Portland, OR users group (PHPdx)

### PR DESCRIPTION
**Pull request by sketchings**

### CODE REVIEW

**Comment by chrisspruck** [comment]
Hi Alena! We're sorting groups by name in this file, so would you mind moving PHPdx down below PHPDublin? Thanks!

**Comment by ramsey** [comment]
Bump. @sketchings, not sure if you saw @chrisspruck's comment above. We'd love to merge this in; we're just trying to keep things in order. Thanks!

**Comment by ramsey** [comment]
Not sure if you saw our request for changes on this a while back, so just double-checking. :smile:

**Comment by ramsey** [comment]
Going to go ahead and merge this in. We can alphabetize it later. :smile: Cheers!

**Pull request merged**
