### PR TITLE
[pt] Add "(pt) Como usar o docker-phpqa"

### PR DESCRIPTION
**Pull request by rogeriopradoj**
Some Brazilian folks on https://t.me/PHPTestFestBrasil are trying to
make some effort to translate all phptestfest.org page, mainly:
@augustohp, @nelsonsar, @lflimeira (https://github.com/augustohp/phptestfest.org/pull).

In the meanwhile, I guess we could provide translated articles in global
website, just prefixing tutorial name with (lang), for example (pt) for
Portuguese and so on.

### CODE REVIEW

**Comment by ramsey** [comment]
I have some ideas about how to structure content for translation. Let me do a little research first, and I'll let you know what I come up with and see if it makes sense to you. Thanks!

**Comment by rogeriopradoj** [comment]
@ramsey , my Brazilian folk, @lflimeira , said that you combined a way to include translated things, alright? Could we use this PR to explain this process clearly?

**Comment by lflimeira** [comment]
Hello @ramsey, could we just create a sub-directory pt-br without a language switcher? We think that it could be a faster resolution for now.

**Comment by ramsey** [comment]
Yes, please. Go ahead. I've been busy lately and not able to help. Sorry.

**Comment by ramsey** [comment]
To clarify, I like the idea of adding a `docs/pt-br/` directory, where we'd reproduce the site translated in that directory. This will make it easy for us to add JavaScript or some other mechanism to automatically redirect to `/pt-br/` if the browser language is detected as pt-BR.

Maybe add a drop-down to the sidebar menu for "Language?"

**Comment by rogeriopradoj** [comment]
Closing in favor of #72

**Pull request closed without merging**
